/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as TopNavRouteRouteImport } from './routes/_top-nav/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as TopNavIndexRouteImport } from './routes/_top-nav/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as TopNavSettingsRouteRouteImport } from './routes/_top-nav/settings/route'
import { Route as TopNavSettingsIndexRouteImport } from './routes/_top-nav/settings/index'
import { Route as TopNavKnowledgeBaseIndexRouteImport } from './routes/_top-nav/knowledge-base/index'
import { Route as TopNavDocumentsIndexRouteImport } from './routes/_top-nav/documents/index'
import { Route as TopNavChatIndexRouteImport } from './routes/_top-nav/chat/index'
import { Route as TopNavAgentsIndexRouteImport } from './routes/_top-nav/agents/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as TopNavSettingsUsersbakRouteImport } from './routes/_top-nav/settings/usersbak'
import { Route as TopNavSettingsRolesbakRouteImport } from './routes/_top-nav/settings/rolesbak'
import { Route as TopNavSettingsProfileRouteImport } from './routes/_top-nav/settings/profile'
import { Route as TopNavSettingsNotificationsRouteImport } from './routes/_top-nav/settings/notifications'
import { Route as TopNavSettingsModelsRouteImport } from './routes/_top-nav/settings/models'
import { Route as TopNavSettingsLogsRouteImport } from './routes/_top-nav/settings/logs'
import { Route as TopNavSettingsGeneralRouteImport } from './routes/_top-nav/settings/general'
import { Route as TopNavSettingsDisplayRouteImport } from './routes/_top-nav/settings/display'
import { Route as TopNavSettingsDataSourcesRouteImport } from './routes/_top-nav/settings/data-sources'
import { Route as TopNavSettingsAppearanceRouteImport } from './routes/_top-nav/settings/appearance'
import { Route as TopNavSettingsApiKeysRouteImport } from './routes/_top-nav/settings/api-keys'
import { Route as TopNavSettingsAccountRouteImport } from './routes/_top-nav/settings/account'
import { Route as TopNavKnowledgeBaseFolderIdRouteImport } from './routes/_top-nav/knowledge-base/$folderId'
import { Route as TopNavChatChatIdRouteImport } from './routes/_top-nav/chat/$chatId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as TopNavSettingsUsersIndexRouteImport } from './routes/_top-nav/settings/users/index'
import { Route as TopNavSettingsTenantsIndexRouteImport } from './routes/_top-nav/settings/tenants/index'
import { Route as TopNavSettingsRolesIndexRouteImport } from './routes/_top-nav/settings/roles/index'
import { Route as TopNavSettingsPermissionsIndexRouteImport } from './routes/_top-nav/settings/permissions/index'
import { Route as TopNavSettingsOrganizationsIndexRouteImport } from './routes/_top-nav/settings/organizations/index'
import { Route as TopNavAgentsAgentIdBuilderRouteImport } from './routes/_top-nav/agents/$agentId/builder'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const TopNavRouteRoute = TopNavRouteRouteImport.update({
  id: '/_top-nav',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TopNavIndexRoute = TopNavIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopNavRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const TopNavSettingsRouteRoute = TopNavSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TopNavRouteRoute,
} as any)
const TopNavSettingsIndexRoute = TopNavSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavKnowledgeBaseIndexRoute =
  TopNavKnowledgeBaseIndexRouteImport.update({
    id: '/knowledge-base/',
    path: '/knowledge-base/',
    getParentRoute: () => TopNavRouteRoute,
  } as any)
const TopNavDocumentsIndexRoute = TopNavDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => TopNavRouteRoute,
} as any)
const TopNavChatIndexRoute = TopNavChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => TopNavRouteRoute,
} as any)
const TopNavAgentsIndexRoute = TopNavAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => TopNavRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const TopNavSettingsUsersbakRoute = TopNavSettingsUsersbakRouteImport.update({
  id: '/usersbak',
  path: '/usersbak',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsRolesbakRoute = TopNavSettingsRolesbakRouteImport.update({
  id: '/rolesbak',
  path: '/rolesbak',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsProfileRoute = TopNavSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsNotificationsRoute =
  TopNavSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavSettingsModelsRoute = TopNavSettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsLogsRoute = TopNavSettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsGeneralRoute = TopNavSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsDisplayRoute = TopNavSettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsDataSourcesRoute =
  TopNavSettingsDataSourcesRouteImport.update({
    id: '/data-sources',
    path: '/data-sources',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavSettingsAppearanceRoute =
  TopNavSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavSettingsApiKeysRoute = TopNavSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavSettingsAccountRoute = TopNavSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => TopNavSettingsRouteRoute,
} as any)
const TopNavKnowledgeBaseFolderIdRoute =
  TopNavKnowledgeBaseFolderIdRouteImport.update({
    id: '/knowledge-base/$folderId',
    path: '/knowledge-base/$folderId',
    getParentRoute: () => TopNavRouteRoute,
  } as any)
const TopNavChatChatIdRoute = TopNavChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => TopNavRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TopNavSettingsUsersIndexRoute =
  TopNavSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavSettingsTenantsIndexRoute =
  TopNavSettingsTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavSettingsRolesIndexRoute =
  TopNavSettingsRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavSettingsPermissionsIndexRoute =
  TopNavSettingsPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavSettingsOrganizationsIndexRoute =
  TopNavSettingsOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => TopNavSettingsRouteRoute,
  } as any)
const TopNavAgentsAgentIdBuilderRoute =
  TopNavAgentsAgentIdBuilderRouteImport.update({
    id: '/agents/$agentId/builder',
    path: '/agents/$agentId/builder',
    getParentRoute: () => TopNavRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof TopNavSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof TopNavIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/chat/$chatId': typeof TopNavChatChatIdRoute
  '/knowledge-base/$folderId': typeof TopNavKnowledgeBaseFolderIdRoute
  '/settings/account': typeof TopNavSettingsAccountRoute
  '/settings/api-keys': typeof TopNavSettingsApiKeysRoute
  '/settings/appearance': typeof TopNavSettingsAppearanceRoute
  '/settings/data-sources': typeof TopNavSettingsDataSourcesRoute
  '/settings/display': typeof TopNavSettingsDisplayRoute
  '/settings/general': typeof TopNavSettingsGeneralRoute
  '/settings/logs': typeof TopNavSettingsLogsRoute
  '/settings/models': typeof TopNavSettingsModelsRoute
  '/settings/notifications': typeof TopNavSettingsNotificationsRoute
  '/settings/profile': typeof TopNavSettingsProfileRoute
  '/settings/rolesbak': typeof TopNavSettingsRolesbakRoute
  '/settings/usersbak': typeof TopNavSettingsUsersbakRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/agents': typeof TopNavAgentsIndexRoute
  '/chat': typeof TopNavChatIndexRoute
  '/documents': typeof TopNavDocumentsIndexRoute
  '/knowledge-base': typeof TopNavKnowledgeBaseIndexRoute
  '/settings/': typeof TopNavSettingsIndexRoute
  '/agents/$agentId/builder': typeof TopNavAgentsAgentIdBuilderRoute
  '/settings/organizations': typeof TopNavSettingsOrganizationsIndexRoute
  '/settings/permissions': typeof TopNavSettingsPermissionsIndexRoute
  '/settings/roles': typeof TopNavSettingsRolesIndexRoute
  '/settings/tenants': typeof TopNavSettingsTenantsIndexRoute
  '/settings/users': typeof TopNavSettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof TopNavIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/chat/$chatId': typeof TopNavChatChatIdRoute
  '/knowledge-base/$folderId': typeof TopNavKnowledgeBaseFolderIdRoute
  '/settings/account': typeof TopNavSettingsAccountRoute
  '/settings/api-keys': typeof TopNavSettingsApiKeysRoute
  '/settings/appearance': typeof TopNavSettingsAppearanceRoute
  '/settings/data-sources': typeof TopNavSettingsDataSourcesRoute
  '/settings/display': typeof TopNavSettingsDisplayRoute
  '/settings/general': typeof TopNavSettingsGeneralRoute
  '/settings/logs': typeof TopNavSettingsLogsRoute
  '/settings/models': typeof TopNavSettingsModelsRoute
  '/settings/notifications': typeof TopNavSettingsNotificationsRoute
  '/settings/profile': typeof TopNavSettingsProfileRoute
  '/settings/rolesbak': typeof TopNavSettingsRolesbakRoute
  '/settings/usersbak': typeof TopNavSettingsUsersbakRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/agents': typeof TopNavAgentsIndexRoute
  '/chat': typeof TopNavChatIndexRoute
  '/documents': typeof TopNavDocumentsIndexRoute
  '/knowledge-base': typeof TopNavKnowledgeBaseIndexRoute
  '/settings': typeof TopNavSettingsIndexRoute
  '/agents/$agentId/builder': typeof TopNavAgentsAgentIdBuilderRoute
  '/settings/organizations': typeof TopNavSettingsOrganizationsIndexRoute
  '/settings/permissions': typeof TopNavSettingsPermissionsIndexRoute
  '/settings/roles': typeof TopNavSettingsRolesIndexRoute
  '/settings/tenants': typeof TopNavSettingsTenantsIndexRoute
  '/settings/users': typeof TopNavSettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_top-nav': typeof TopNavRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_top-nav/settings': typeof TopNavSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_top-nav/': typeof TopNavIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_top-nav/chat/$chatId': typeof TopNavChatChatIdRoute
  '/_top-nav/knowledge-base/$folderId': typeof TopNavKnowledgeBaseFolderIdRoute
  '/_top-nav/settings/account': typeof TopNavSettingsAccountRoute
  '/_top-nav/settings/api-keys': typeof TopNavSettingsApiKeysRoute
  '/_top-nav/settings/appearance': typeof TopNavSettingsAppearanceRoute
  '/_top-nav/settings/data-sources': typeof TopNavSettingsDataSourcesRoute
  '/_top-nav/settings/display': typeof TopNavSettingsDisplayRoute
  '/_top-nav/settings/general': typeof TopNavSettingsGeneralRoute
  '/_top-nav/settings/logs': typeof TopNavSettingsLogsRoute
  '/_top-nav/settings/models': typeof TopNavSettingsModelsRoute
  '/_top-nav/settings/notifications': typeof TopNavSettingsNotificationsRoute
  '/_top-nav/settings/profile': typeof TopNavSettingsProfileRoute
  '/_top-nav/settings/rolesbak': typeof TopNavSettingsRolesbakRoute
  '/_top-nav/settings/usersbak': typeof TopNavSettingsUsersbakRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_top-nav/agents/': typeof TopNavAgentsIndexRoute
  '/_top-nav/chat/': typeof TopNavChatIndexRoute
  '/_top-nav/documents/': typeof TopNavDocumentsIndexRoute
  '/_top-nav/knowledge-base/': typeof TopNavKnowledgeBaseIndexRoute
  '/_top-nav/settings/': typeof TopNavSettingsIndexRoute
  '/_top-nav/agents/$agentId/builder': typeof TopNavAgentsAgentIdBuilderRoute
  '/_top-nav/settings/organizations/': typeof TopNavSettingsOrganizationsIndexRoute
  '/_top-nav/settings/permissions/': typeof TopNavSettingsPermissionsIndexRoute
  '/_top-nav/settings/roles/': typeof TopNavSettingsRolesIndexRoute
  '/_top-nav/settings/tenants/': typeof TopNavSettingsTenantsIndexRoute
  '/_top-nav/settings/users/': typeof TopNavSettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/chat/$chatId'
    | '/knowledge-base/$folderId'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/data-sources'
    | '/settings/display'
    | '/settings/general'
    | '/settings/logs'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/rolesbak'
    | '/settings/usersbak'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/tasks'
    | '/users'
    | '/agents'
    | '/chat'
    | '/documents'
    | '/knowledge-base'
    | '/settings/'
    | '/agents/$agentId/builder'
    | '/settings/organizations'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/tenants'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/chat/$chatId'
    | '/knowledge-base/$folderId'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/data-sources'
    | '/settings/display'
    | '/settings/general'
    | '/settings/logs'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/rolesbak'
    | '/settings/usersbak'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/tasks'
    | '/users'
    | '/agents'
    | '/chat'
    | '/documents'
    | '/knowledge-base'
    | '/settings'
    | '/agents/$agentId/builder'
    | '/settings/organizations'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/tenants'
    | '/settings/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_top-nav'
    | '/clerk'
    | '/_top-nav/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_top-nav/'
    | '/_authenticated/errors/$error'
    | '/_top-nav/chat/$chatId'
    | '/_top-nav/knowledge-base/$folderId'
    | '/_top-nav/settings/account'
    | '/_top-nav/settings/api-keys'
    | '/_top-nav/settings/appearance'
    | '/_top-nav/settings/data-sources'
    | '/_top-nav/settings/display'
    | '/_top-nav/settings/general'
    | '/_top-nav/settings/logs'
    | '/_top-nav/settings/models'
    | '/_top-nav/settings/notifications'
    | '/_top-nav/settings/profile'
    | '/_top-nav/settings/rolesbak'
    | '/_top-nav/settings/usersbak'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_top-nav/agents/'
    | '/_top-nav/chat/'
    | '/_top-nav/documents/'
    | '/_top-nav/knowledge-base/'
    | '/_top-nav/settings/'
    | '/_top-nav/agents/$agentId/builder'
    | '/_top-nav/settings/organizations/'
    | '/_top-nav/settings/permissions/'
    | '/_top-nav/settings/roles/'
    | '/_top-nav/settings/tenants/'
    | '/_top-nav/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  TopNavRouteRoute: typeof TopNavRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_top-nav': {
      id: '/_top-nav'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TopNavRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_top-nav/': {
      id: '/_top-nav/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TopNavIndexRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_top-nav/settings': {
      id: '/_top-nav/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TopNavSettingsRouteRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/_top-nav/settings/': {
      id: '/_top-nav/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof TopNavSettingsIndexRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/knowledge-base/': {
      id: '/_top-nav/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof TopNavKnowledgeBaseIndexRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/_top-nav/documents/': {
      id: '/_top-nav/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof TopNavDocumentsIndexRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/_top-nav/chat/': {
      id: '/_top-nav/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof TopNavChatIndexRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/_top-nav/agents/': {
      id: '/_top-nav/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof TopNavAgentsIndexRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_top-nav/settings/usersbak': {
      id: '/_top-nav/settings/usersbak'
      path: '/usersbak'
      fullPath: '/settings/usersbak'
      preLoaderRoute: typeof TopNavSettingsUsersbakRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/rolesbak': {
      id: '/_top-nav/settings/rolesbak'
      path: '/rolesbak'
      fullPath: '/settings/rolesbak'
      preLoaderRoute: typeof TopNavSettingsRolesbakRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/profile': {
      id: '/_top-nav/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof TopNavSettingsProfileRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/notifications': {
      id: '/_top-nav/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof TopNavSettingsNotificationsRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/models': {
      id: '/_top-nav/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof TopNavSettingsModelsRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/logs': {
      id: '/_top-nav/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof TopNavSettingsLogsRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/general': {
      id: '/_top-nav/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof TopNavSettingsGeneralRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/display': {
      id: '/_top-nav/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof TopNavSettingsDisplayRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/data-sources': {
      id: '/_top-nav/settings/data-sources'
      path: '/data-sources'
      fullPath: '/settings/data-sources'
      preLoaderRoute: typeof TopNavSettingsDataSourcesRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/appearance': {
      id: '/_top-nav/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof TopNavSettingsAppearanceRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/api-keys': {
      id: '/_top-nav/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof TopNavSettingsApiKeysRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/account': {
      id: '/_top-nav/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof TopNavSettingsAccountRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/knowledge-base/$folderId': {
      id: '/_top-nav/knowledge-base/$folderId'
      path: '/knowledge-base/$folderId'
      fullPath: '/knowledge-base/$folderId'
      preLoaderRoute: typeof TopNavKnowledgeBaseFolderIdRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/_top-nav/chat/$chatId': {
      id: '/_top-nav/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof TopNavChatChatIdRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_top-nav/settings/users/': {
      id: '/_top-nav/settings/users/'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof TopNavSettingsUsersIndexRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/tenants/': {
      id: '/_top-nav/settings/tenants/'
      path: '/tenants'
      fullPath: '/settings/tenants'
      preLoaderRoute: typeof TopNavSettingsTenantsIndexRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/roles/': {
      id: '/_top-nav/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof TopNavSettingsRolesIndexRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/permissions/': {
      id: '/_top-nav/settings/permissions/'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof TopNavSettingsPermissionsIndexRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/settings/organizations/': {
      id: '/_top-nav/settings/organizations/'
      path: '/organizations'
      fullPath: '/settings/organizations'
      preLoaderRoute: typeof TopNavSettingsOrganizationsIndexRouteImport
      parentRoute: typeof TopNavSettingsRouteRoute
    }
    '/_top-nav/agents/$agentId/builder': {
      id: '/_top-nav/agents/$agentId/builder'
      path: '/agents/$agentId/builder'
      fullPath: '/agents/$agentId/builder'
      preLoaderRoute: typeof TopNavAgentsAgentIdBuilderRouteImport
      parentRoute: typeof TopNavRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TopNavSettingsRouteRouteChildren {
  TopNavSettingsAccountRoute: typeof TopNavSettingsAccountRoute
  TopNavSettingsApiKeysRoute: typeof TopNavSettingsApiKeysRoute
  TopNavSettingsAppearanceRoute: typeof TopNavSettingsAppearanceRoute
  TopNavSettingsDataSourcesRoute: typeof TopNavSettingsDataSourcesRoute
  TopNavSettingsDisplayRoute: typeof TopNavSettingsDisplayRoute
  TopNavSettingsGeneralRoute: typeof TopNavSettingsGeneralRoute
  TopNavSettingsLogsRoute: typeof TopNavSettingsLogsRoute
  TopNavSettingsModelsRoute: typeof TopNavSettingsModelsRoute
  TopNavSettingsNotificationsRoute: typeof TopNavSettingsNotificationsRoute
  TopNavSettingsProfileRoute: typeof TopNavSettingsProfileRoute
  TopNavSettingsRolesbakRoute: typeof TopNavSettingsRolesbakRoute
  TopNavSettingsUsersbakRoute: typeof TopNavSettingsUsersbakRoute
  TopNavSettingsIndexRoute: typeof TopNavSettingsIndexRoute
  TopNavSettingsOrganizationsIndexRoute: typeof TopNavSettingsOrganizationsIndexRoute
  TopNavSettingsPermissionsIndexRoute: typeof TopNavSettingsPermissionsIndexRoute
  TopNavSettingsRolesIndexRoute: typeof TopNavSettingsRolesIndexRoute
  TopNavSettingsTenantsIndexRoute: typeof TopNavSettingsTenantsIndexRoute
  TopNavSettingsUsersIndexRoute: typeof TopNavSettingsUsersIndexRoute
}

const TopNavSettingsRouteRouteChildren: TopNavSettingsRouteRouteChildren = {
  TopNavSettingsAccountRoute: TopNavSettingsAccountRoute,
  TopNavSettingsApiKeysRoute: TopNavSettingsApiKeysRoute,
  TopNavSettingsAppearanceRoute: TopNavSettingsAppearanceRoute,
  TopNavSettingsDataSourcesRoute: TopNavSettingsDataSourcesRoute,
  TopNavSettingsDisplayRoute: TopNavSettingsDisplayRoute,
  TopNavSettingsGeneralRoute: TopNavSettingsGeneralRoute,
  TopNavSettingsLogsRoute: TopNavSettingsLogsRoute,
  TopNavSettingsModelsRoute: TopNavSettingsModelsRoute,
  TopNavSettingsNotificationsRoute: TopNavSettingsNotificationsRoute,
  TopNavSettingsProfileRoute: TopNavSettingsProfileRoute,
  TopNavSettingsRolesbakRoute: TopNavSettingsRolesbakRoute,
  TopNavSettingsUsersbakRoute: TopNavSettingsUsersbakRoute,
  TopNavSettingsIndexRoute: TopNavSettingsIndexRoute,
  TopNavSettingsOrganizationsIndexRoute: TopNavSettingsOrganizationsIndexRoute,
  TopNavSettingsPermissionsIndexRoute: TopNavSettingsPermissionsIndexRoute,
  TopNavSettingsRolesIndexRoute: TopNavSettingsRolesIndexRoute,
  TopNavSettingsTenantsIndexRoute: TopNavSettingsTenantsIndexRoute,
  TopNavSettingsUsersIndexRoute: TopNavSettingsUsersIndexRoute,
}

const TopNavSettingsRouteRouteWithChildren =
  TopNavSettingsRouteRoute._addFileChildren(TopNavSettingsRouteRouteChildren)

interface TopNavRouteRouteChildren {
  TopNavSettingsRouteRoute: typeof TopNavSettingsRouteRouteWithChildren
  TopNavIndexRoute: typeof TopNavIndexRoute
  TopNavChatChatIdRoute: typeof TopNavChatChatIdRoute
  TopNavKnowledgeBaseFolderIdRoute: typeof TopNavKnowledgeBaseFolderIdRoute
  TopNavAgentsIndexRoute: typeof TopNavAgentsIndexRoute
  TopNavChatIndexRoute: typeof TopNavChatIndexRoute
  TopNavDocumentsIndexRoute: typeof TopNavDocumentsIndexRoute
  TopNavKnowledgeBaseIndexRoute: typeof TopNavKnowledgeBaseIndexRoute
  TopNavAgentsAgentIdBuilderRoute: typeof TopNavAgentsAgentIdBuilderRoute
}

const TopNavRouteRouteChildren: TopNavRouteRouteChildren = {
  TopNavSettingsRouteRoute: TopNavSettingsRouteRouteWithChildren,
  TopNavIndexRoute: TopNavIndexRoute,
  TopNavChatChatIdRoute: TopNavChatChatIdRoute,
  TopNavKnowledgeBaseFolderIdRoute: TopNavKnowledgeBaseFolderIdRoute,
  TopNavAgentsIndexRoute: TopNavAgentsIndexRoute,
  TopNavChatIndexRoute: TopNavChatIndexRoute,
  TopNavDocumentsIndexRoute: TopNavDocumentsIndexRoute,
  TopNavKnowledgeBaseIndexRoute: TopNavKnowledgeBaseIndexRoute,
  TopNavAgentsAgentIdBuilderRoute: TopNavAgentsAgentIdBuilderRoute,
}

const TopNavRouteRouteWithChildren = TopNavRouteRoute._addFileChildren(
  TopNavRouteRouteChildren,
)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  TopNavRouteRoute: TopNavRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
